# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 14:56
from __future__ import unicode_literals

import ask_me.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0002_auto_20180322_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerManager',
        ),
        migrations.DeleteModel(
            name='QuestionManager',
        ),
        migrations.DeleteModel(
            name='TagManager',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ask_me.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
