# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0003_auto_20180322_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='ask_me.Tag', verbose_name="Question's Tags"),
        ),
    ]
