# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0004_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ask_me.Question', verbose_name="Answer's Question"),
        ),
    ]
