# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0010_auto_20180410_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='ask_me.Tag', verbose_name="Question's Tags"),
        ),
    ]
