# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0011_auto_20180411_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(default='src/default_avatar.png', upload_to='%Y/%m/%d/', verbose_name="User's Avatar"),
        ),
    ]
